### ISSUE TITLE
How to use this package

### ISSUE THREAD

**Issue by TimDurward** [yieldbits/probot#2]
I couldn't have find any documentation on how to use this package. Just wanted to check in to see if I was missing something. Thanks!

**Comment by akshayKrSingh** [comment]
@TimDurward: Hi, I couldn't find the chance to add documentation for it. I'll add it by the end of the week. Thanks for reaching out with the issue.

**Comment by null-key** [comment]
Hi, apologies for the late reply, I was doing some refactoring of the initial module. 

This module has been moved to [yieldbits/nestjs/probot](https://github.com/yieldbits/nestjs)

* new package `@yieldbits/probot` [documentation](https://yieldbits.github.io/nestjs/docs/documentation/probot/)
* new repository location for the package: https://github.com/yieldbits/nestjs/tree/main/packages/probot

I will deprecate `@nestjs-shared/probot` package in support for `@yieldbits/probot` package as it's been refactored to be simpler to use and less complicated than the current one.

Please visit our documentation website and share your feedback. Thank you 🙂 

-- @Ryan-Singh-UKG @TimDurward: thank you for reaching out !! Hope the documentation helps.
